# fly.toml file generated for zkwordo-backend on 2023-04-23T17:45:59+01:00

app = "zkwordo-backend"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "lhr"
processes = []

[env]
  PORT = "8080"
  ZK_WORDO_ADDRESS = "0x4b79635f3cd08c704db30181ca2b4d1415b472da"
  WORDS_PATH = "/app/data/words.json"
  ZK_WASM_PATH = "/app/data/zkwordo.wasm"
  ZK_ZKEY_PATH = "/app/data/zkwordo.zkey"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
