name: Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
on:
  push:
    branches:
    - deploy
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Prepare contract artifacts
      run: npm install && npm run compile && npm run wagmi-generate

    # deploy backend
    - run: ./utils/decrypt-secrets.sh ${{ secrets.PASSPHRASE }}
    - run: npm run prepare-backend-data
    - uses: superfly/flyctl-actions/setup-flyctl@master
    - uses: docker/setup-buildx-action@v2
    - run: flyctl deploy --local-only
      working-directory: backend

    # deploy webapp
    - name: Install Vercel CLI
      run: npm install --global vercel@latest
    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
    - name: Build Project Artifacts
      run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} ./webapp
    - name: Deploy Project Artifacts to Vercel
      run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
